services:
  voice-assistant:
    build:
      context: .
      dockerfile: Containerfile
    volumes:
      - .:/app:Z
    environment:
      - DATA_DIR=/app/data
    # Let the entrypoint script handle the command
    # The .env file will be mounted from the host and loaded by the application
    env_file:
      - .env
    stdin_open: true  # equivalent to -i
    tty: true         # equivalent to -t
    init: true        # Use init process for proper signal handling